### ISSUE TITLE
[Backend] No deja conquistar si se ha atacado a los campesinos 

### ISSUE THREAD

**Issue by MrNachoM** [Javierif/Guaranpis-tickets#11]
![image](https://user-images.githubusercontent.com/71265108/99289602-77071100-283d-11eb-8475-5478d487ebf6.png)

No puedo estar seguro de que sea así xq solo había 1 grupo de campesinos, pero juraría que ataqué, los eliminé, y ya no me deja conquistar porque dice que ya lo intenté ese turno

**Comment by MrNachoM** [comment]
confirmado el bug

**Comment by Javierif** [comment]
Fixed
