### ISSUE TITLE
[Backend] No puede construir edificio economico 

### ISSUE THREAD

**Issue by MrNachoM** [Javierif/Guaranpis-tickets#14]
![image](https://user-images.githubusercontent.com/71265108/99297824-11208680-2849-11eb-8757-c9f694ac4806.png)
porque dice que tienes un edificio defensivo mejor

**Comment by MrNachoM** [comment]
Hay un personaje religiodo en el feudo

**Comment by Javierif** [comment]
![image](https://user-images.githubusercontent.com/10996645/99382861-6bfbc180-28cd-11eb-8004-465ce548b69e.png)
Probado y funcionó sin problemas.. cierro incidencia pero hay que estar vigilantes
