### ISSUE TITLE
[Javascript] Cuartel unir estadisticas en una sola columna

### ISSUE THREAD

**Issue by Javierif** [Javierif/Guaranpis-tickets#21]
![image](https://user-images.githubusercontent.com/10996645/99375767-6352bd80-28c4-11eb-8bdd-37a2da7fcde7.png)
Poner como columna de estadísticas y ponerle un iconito a movimiento

**Comment by MrNachoM** [comment]
![image](https://user-images.githubusercontent.com/71265108/99434789-7f2f8100-290f-11eb-86e3-fdede242c20a.png)
