### ISSUE TITLE
[Backend] Cuartel tiene repetidas tropas de marineros

### ISSUE THREAD

**Issue by MrNachoM** [Javierif/Guaranpis-tickets#24]
https://beta.guaranpis.es//api/mocks/info/feudos/getfeudo.php?x=29&y=11

![image](https://user-images.githubusercontent.com/71265108/99429228-f6f9ad80-2907-11eb-87d6-5e4093a7f5bd.png)

{
"TIPO": 3,
"NOMBRE": "Marineros",
"PRECIO": 150,
"SUELDO": 256,
"ATAQUE": 6,
"VIDA": 50,
"REDUCCIONBAJAS": 0,
"VELOCIDAD": 2,
"PROFESIONAL": 1,
"EQUIPOS": 1,
"LUGAR": 2,
"EQUIPOSADQUIRIDOS": 0
},
{
"TIPO": 3,
"NOMBRE": "Marineros",
"PRECIO": 150,
"SUELDO": 256,
"ATAQUE": 6,
"VIDA": 50,
"REDUCCIONBAJAS": 0,
"VELOCIDAD": 2,
"PROFESIONAL": 1,
"EQUIPOS": 1,
"LUGAR": 2,
"EQUIPOSADQUIRIDOS": 0
},

**Comment by Javierif** [comment]
Fixed
