### ISSUE TITLE
Error Al Construir

### ISSUE THREAD

**Issue by MrNachoM** [Javierif/Guaranpis-tickets#4]
![image](https://user-images.githubusercontent.com/71265108/99192705-9128ec80-2774-11eb-845b-5456a4baa779.png)

**Comment by Javierif** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/10996645/99240668-19eb6b00-27fd-11eb-9a25-7d656ad2b427.png)

Se ha actualizado los endpoints de reparar y destruir, ahora hay que enviarle únicamente el parámetro id que es el id del edificio a reparar/destruir:
![image](https://user-images.githubusercontent.com/10996645/99240734-31c2ef00-27fd-11eb-84c2-5a51b70140d5.png)
