### ISSUE TITLE
[Backend] Accion CUARTEL es 1 en feudo que no tiene costa, no es ppal y sin edificio

### ISSUE THREAD

**Issue by MrNachoM** [Javierif/Guaranpis-tickets#7]
https://beta.guaranpis.es//api/mocks/info/feudos/getfeudo.php?x=158&y=388

![image](https://user-images.githubusercontent.com/71265108/99235256-ea853000-27f5-11eb-97a5-f7615cdbab4d.png)

**Comment by Javierif** [comment]
fixed
